[tool.ruff]
line-length = 88
select = ["E", "W", "F", "I", "N"]
ignore = ["E501", "I001", "F401"]

[tool.black]
line-length = 88
target-version = ['py312']
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''
